name: "Butler Burton"
color: "#46D9FF"
webhook_url: ""
notifications: true
vab_msg: "Jag vabbar idag, försök hålla skutan flytande så är jag tillbaks imorgon"
report:
    path: "/root/.butlerburton/"
    update: true
    checkin_col: "C"
    checkout_col: "D"
    lunch_col: "F"
    bl_lunch_col: "I"
    overtime_col: "R"
    vab_col: "L"
    afk_col: "G"

